development:
  bucket: shortslide_development
  access_key_id: ENV['AWS_KEY']
  secret_access_key: ENV['AWS_SECRET']
  s3_host_name: "s3-ap-northeast-1.amazonaws.com"
test:
  bucket: shortslide_test
  access_key_id: ENV['AWS_KEY']
  secret_access_key: ENV['AWS_SECRET']
  s3_host_name: "s3-ap-northeast-1.amazonaws.com"
production:
  bucket: shortslide_production
  access_key_id: ENV['AWS_KEY']
  secret_access_key: ENV['AWS_SECRET']
  s3_host_name: "s3-ap-northeast-1.amazonaws.com"
